### ISSUE TITLE
Znalezienie i wypełnienie bazy danych 

### ISSUE THREAD

**Issue by dawidPyth** [damianswist/pite_project#1]
Znalezienie odpowiedniej bazy danych oraz integracja z apką.

**Comment by dawidPyth** [comment]
Znalazłem słowniki pol-eng i odwrotny. Rozkminiałem tez tą baze i myślę że 4 tabelki nam wystarczą na początek
![tabelki](https://cloud.githubusercontent.com/assets/26218341/25410223/bdcccc80-2a15-11e7-94f6-5713eea703c3.JPG)

Ale nadal troche hejcę sqla bo np w tabelce user_progress liczba elementow w arrayu będzie różna dla różnych userów a nie mam pewności czy tak można (wydaje mi się że nie). (Mongo? :P) Trzeba pomyśleć.

**Comment by klaudiagadek** [comment]
gdzie masz ten słownik ? wrzucałeś go gdzieś ? 
myślę że trzeba pomyśleć jeszcze nad podziąłem tabel, bo to jest trohcę mało efektywne.

**Comment by dawidPyth** [comment]
Na facebooka. Tutaj nie chce się wrzucić.

**Comment by klaudiagadek** [comment]
Jak tam baza danych idzie :) jakies nowe info ? zostajemy przy tej starej Dawida ?

**Comment by dawidPyth** [comment]
Troche zmieniona koncepcja: 
![tabela](https://cloud.githubusercontent.com/assets/26218341/25569180/2fa84384-2e12-11e7-8a33-f80868792fad.JPG)
Zmigrowałem baze: są słowa i tłumaczenia - baze wrzuce na fb
