### ISSUE TITLE
Stworzenie formularza do rejestracji użytkowników

### ISSUE THREAD

**Issue by dawidPyth** [damianswist/pite_project#3]
Stworzenie widoku i panelu użytkownika

**Comment by klaudiagadek** [comment]
Co mam dokladnie zrobic, teraz mam login rejestracje i wylogowanie usera. Widoki sa slabe juz mowie ale licze ze Dawid jak zorbi strone glowna to sie dostosuje

**Comment by dawidPyth** [comment]
Rozumiem że zapisuje usera do bazy i potem sprawdza czy się zgadza?

**Comment by klaudiagadek** [comment]
no tak, zróbcie mi review :P

**Comment by klaudiagadek** [comment]
@damianswist 
@dawidPyth 
Rewiev!
