### ISSUE TITLE
Dodawanie sugestii tłumaczeń przez użytkowników

### ISSUE THREAD

**Issue by dawidPyth** [damianswist/pite_project#5]
Dodawanie sugestii tłumaczeń i akceptacja przez admina.

**Comment by klaudiagadek** [comment]
ok na początek:
zrób sobie widok podbny do tego:
https://translate.google.pl/?hl=pl
tylko poniżesz wszystkiego dodaj button zasugeruj tłumaczenie i żeby tam było obok tego okenka pole do podania tego tłumaczenia

**Comment by klaudiagadek** [comment]
potem masz zrobić w kodzie:
pobierać to tłumaczenie i słowo i wysyłać na maila: na początek możesz podac swojego maila niech Ci spamuje.

**Comment by dawidPyth** [comment]
sugestie sa wysyłane mailem, feature dostępny po wyszukaniu słowa w słowniku
